# Site settings
title:       patrickmowrer.com
email:       
author:      Patrick Mowrer
description: 
baseurl:     ""
url:         http://patrickmowrer.com
permalink:   /:year/:month/:day/:title

# Google analytics
google_analytics: UA-11923307-2

# Disqus
disqus_shortname: patrickmowrer

# RSS
feed_url: http://feeds.feedburner.com/patrickmowrercom

# Optional features
animated:           true
show_related_posts: false

# Social icons
show_social_icons:  true
github_username:    pmowrer
twitter_username:   stiggler
google_plus_id:
linkedin_username:  patrickmowrer
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true